FROM nginx:1.25.3-alpine-slim

# this is actual only for minimal version of parent image
RUN adduser -u 1000 -D -S -G www-data www-data

RUN mkdir /var/www
RUN chown -R www-data:www-data /var/www
COPY config/nginx/nginx.conf /etc/nginx/
COPY config/nginx/ssl/default.conf.ssl_letsencrypt_first_run.template /etc/nginx/templates/default.conf.template