FROM nginx:latest

COPY config/nginx/nginx.conf /etc/nginx/
COPY config/nginx/no_ssl/default.conf.no_ssl /etc/nginx/conf.d/
COPY config/nginx/ssl/default.conf.ssl /etc/nginx/conf.d/
COPY config/nginx/peresvet /etc/nginx/conf.d/

WORKDIR /etc/nginx/conf.d
RUN ln -s ./default.conf.no_ssl ./default.conf
