FROM nginx:1.25.3-alpine3.18-slim

COPY config/nginx/nginx.conf /etc/nginx/
COPY config/nginx/no_ssl/default.conf.no_ssl.template /etc/nginx/templates/default.conf.template
#COPY config/nginx/ssl/default.conf.ssl.template /etc/nginx/templates/
COPY config/nginx/peresvet /etc/nginx/templates/

#WORKDIR /etc/nginx/conf.d
#RUN rm default.conf
#RUN ln -s ./default.conf.no_ssl ./default.conf
