#FROM grafana/grafana-enterprise
FROM grafana/grafana-enterprise:11.2.2-ubuntu

EXPOSE 3000
ARG NGINX_HOST

RUN mkdir /var/lib/grafana/dashboards
COPY config/grafana/grafana.ini /etc/grafana/
COPY src/configurator_grafana/Configurator.json /var/lib/grafana/dashboards
COPY config/grafana/provisioning/dashboards/prs.yaml /etc/grafana/provisioning/dashboards
COPY config/grafana/provisioning/datasources/prs.yaml /etc/grafana/provisioning/datasources
RUN sed -i "s/NGINX_HOST/$NGINX_HOST/" /etc/grafana/provisioning/datasources/prs.yaml

COPY config/grafana/logos/mpc.png /usr/share/grafana/public/img/fav32.png
COPY config/grafana/logos/mpc.png /usr/share/grafana/public/img/apple-touch-icon.png
COPY config/grafana/logos/peresvet.svg /usr/share/grafana/public/img/grafana_icon.svg

RUN find /usr/share/grafana/public/build/ -name *.js \
    -exec sed -i 's|AppTitle="Grafana"|AppTitle="Пересвет"|g' {} \;

RUN find /usr/share/grafana/public/build/ -name *.js \
    -exec sed -i 's|LoginTitle="Welcome to Grafana"|LoginTitle="Пересвет"|g' {} \;

USER root

RUN mkdir /usr/share/grafana/public/assets
WORKDIR /usr/share/grafana/public/assets
ADD src/configurator/public/assets/css/ css
ADD src/configurator/public/assets/pics/ pics
ADD src/configurator/public/assets/webfonts/ webfonts
