FROM nginx/unit:1.28.0-python3.10

ENV LDAP_ORGANISATION mycompany
ENV LDAP_DOMAIN mycompany.com
ENV LDAP_ADMIN_PASSWORD 123456

#RUN rm /bin/sh && ln -s /bin/bash /bin/sh

WORKDIR /home
RUN pip3 install pipenv
RUN apt-get update && apt-get install -y --no-install-recommends gcc \
    build-essential python3-dev \
    libldap2-dev libsasl2-dev tox lcov valgrind

RUN bash -c "DEBIAN_FRONTEND=noninteractive apt install -q -y slapd ldap-utils"

# для каждого сервиса создадим свой каталог -------------------
WORKDIR /usr/src
RUN mkdir dataStorages_api_crud dataStorages_model_crud dataStorages_app_psql dataStorages_app_vm
COPY src/services/dataStorages/api_crud/Pipfile /usr/src/dataStorages_api_crud/
COPY src/services/dataStorages/model_crud/Pipfile /usr/src/dataStorages_model_crud/
COPY src/services/dataStorages/app/postgresql/Pipfile /usr/src/dataStorages_app_psql/
COPY src/services/dataStorages/app/victoriametrics/Pipfile /usr/src/dataStorages_app_vm/

WORKDIR /usr/src/dataStorages_api_crud
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

WORKDIR /usr/src/dataStorages_model_crud
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

WORKDIR /usr/src/dataStorages_app_psql
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

WORKDIR /usr/src/dataStorages_app_vm
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy

RUN apt-get -y purge slapd

RUN addgroup --gid 1024 volume_group
RUN usermod -a -G volume_group unit

# устранение ошибки, когда приложение FastAPI из-под nginx.unit не может
# присоединиться к базе PostgreSQL
RUN usermod -a -G root unit
RUN chmod g+wx /root

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY docker/docker-files/dataStorages/config_nginx.unit_dataStorages.all.json /docker-entrypoint.d/

# копируем исходники --------------------------------------------
ADD src/common/ /usr/src/dataStorages_api_crud/src/common
COPY src/__init__.py /usr/src/dataStorages_api_crud/src/
RUN rm -r -f /usr/src/dataStorages_api_crud/src/common/__pycache__
WORKDIR /usr/src/dataStorages_api_crud/src
RUN mkdir services
COPY src/services/__init__.py /usr/src/dataStorages_api_crud/src/services/
WORKDIR /usr/src/dataStorages_api_crud/src/services
ADD src/services/dataStorages/api_crud dataStorages/api_crud
RUN rm -r -f /usr/src/dataStorages_api_crud/src/services/dataStorages/api_crud/__pycache__

ADD src/common/ /usr/src/dataStorages_model_crud/src/common
COPY src/__init__.py /usr/src/dataStorages_model_crud/src/
RUN rm -r -f /usr/src/dataStorages_model_crud/src/common/__pycache__
WORKDIR /usr/src/dataStorages_model_crud/src
RUN mkdir services
COPY src/services/__init__.py /usr/src/dataStorages_model_crud/src/services/
WORKDIR /usr/src/dataStorages_model_crud/src/services
ADD src/services/dataStorages/model_crud dataStorages/model_crud
RUN rm -r -f /usr/src/dataStorages_model_crud/src/services/dataStorages/model_crud/__pycache__

ADD src/common/ /usr/src/dataStorages_app_psql/src/common
COPY src/__init__.py /usr/src/dataStorages_app_psql/src/
RUN rm -r -f /usr/src/dataStorages_app_psql/src/common/__pycache__
WORKDIR /usr/src/dataStorages_app_psql/src
RUN mkdir -p services/DataStorages/app
COPY src/services/__init__.py /usr/src/dataStorages_app_psql/src/services/
COPY src/services/dataStorages/__init__.py /usr/src/dataStorages_app_psql/src/services/dataStorages/
COPY src/services/dataStorages/app/__init__.py /usr/src/dataStorages_app_psql/src/services/dataStorages/app/
WORKDIR /usr/src/dataStorages_app_psql/src/services
ADD src/services/dataStorages/app/postgresql dataStorages/app/postgresql
RUN rm -r -f /usr/src/dataStorages_app_psql/src/services/dataStorages/app/postgresql/__pycache__

ADD src/common/ /usr/src/dataStorages_app_vm/src/common
COPY src/__init__.py /usr/src/dataStorages_app_vm/src/
RUN rm -r -f /usr/src/dataStorages_app_vm/src/common/__pycache__
WORKDIR /usr/src/dataStorages_app_vm/src
RUN mkdir -p services/dataStorages/app
COPY src/services/__init__.py /usr/src/dataStorages_app_vm/src/services/
COPY src/services/dataStorages/__init__.py /usr/src/dataStorages_app_vm/src/services/dataStorages/
COPY src/services/dataStorages/app/__init__.py /usr/src/dataStorages_app_vm/src/services/dataStorages/app/
WORKDIR /usr/src/dataStorages_app_vm/src/services
ADD src/services/dataStorages/app/victoriametrics dataStorages/app/victoriametrics
RUN rm -r -f /usr/src/dataStorages_app_vm/src/services/dataStorages/app/victoriametrics/__pycache__
# ------------------------------------------------------------

EXPOSE 82

COPY docker/docker-files/common/debug_setup.py /usr/src
COPY --chmod=777 docker/docker-files/common/run_debug_setup.sh /docker-entrypoint.d/
