# pull official base image
FROM python:3.9

# set work directory
WORKDIR /usr/src

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# copy requirements file
COPY ./src/requirements.txt /usr/src/requirements.txt

# install dependencies
RUN pip install --no-cache-dir --upgrade -r /usr/src/requirements.txt

# copy project
COPY ./src /usr/src/

#
#CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
