FROM ubuntu:22.04

# postgresql -----------------------------------------------------------------
ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
ENV POSTGRES_DB ${POSTGRES_DB}
ENV TZ ${TIME_ZONE}
RUN apt-get install postgresql
# ----------------------------------------------------------------------------
EXPOSE 5432
