services:
  redis:
    container_name: prs-redis
    restart: always

  rabbitmq:
    container_name: prs-rabbitmq
    restart: always

  ldap:
    container_name: prs-openldap
    restart: always

  psql:
    container_name: prs-psql
    restart: always

  grafana:
    container_name: prs-grafana
    restart: always

  one_app:
    container_name: prs-one-app
    restart: always

  nginx_one_app:
    container_name: prs-nginx-one-app
    restart: always